export const RealEstate = "/real_estates";
export const GetStreets = "/get-all-streets";
export const GetCities = "/cities";
export const GetSection = "/sections";
export const AddToFavourite = "/wish_list";
export const GetFavourite = "/get-wishlist";
export const Reporting = "/reporting";
export const AddAD = "/add-real_estate";
export const RealEstateById = "/real_estate";
export const RealEstateList = "/real_estates-list";
export const GetAllKind = "/kinds";
export const Profile = "/profile";
export const Authenticate = "/authenticate";
export const AddOrder = "/add-order";
export const Search = "/search";
export const DeleteRealEstate = "/real_estate-delete";
export const UpdateRealEstate = "/update-real_estate";
export const Rate = (id) => `/rating/${id}`;
export const RefreshRealEstate = (id) => `/real-estates-refresh/${id}`;
export const SendMessage = `/send-messages`;
export const GetMessage = (id) => `/messages/${id}`;
export const RentRealEstate = "/rents-map";
export const GetUserForChat = "/getUserMessageIds";
